AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Daily Slack notifications for open GitHub pull requests'
Resources:
  slackprreminder:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: execution-handler.execute
      Runtime: nodejs8.10
      CodeUri: .
      Description: 'Daily Slack notifications for open GitHub pull requests'
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::508593216131:role/lambda_basic_execution'
      Events:
        MorningTime:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 ? * MON-FRI *)
